### PR TITLE
[ENH] Add additional mCCA example

### PR DESCRIPTION
**Pull request by johnkylecooper**
Hi, thanks for the amazing toolbox! I would like to add an additional example using the MCCA implementation in python-meegkit since I was initially having trouble understanding how the implementation is used to extract an underlying signal from concatenated data matrices. Maybe this will help others when applying more complex signals to the MCCA function.
The example is example #1 taken from de Cheveigné et al., 2018. I believe that the code is correct and reproduces the results shown in Figure 4. Note: this is my first pull request, so I apologize in advance if anything isn't properly implemented.

### CODE REVIEW

**Comment by johnkylecooper** [comment]
Hi, I'm happy to see that my pr has passed all but one of the tests. With regards to the test that failed, I'm not sure I can fix it on my end. Here is the error:

```
remote: Permission to nbara/python-meegkit.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/nbara/python-meegkit/': The requested URL returned error: 403
```

Best,
John Kyle

**Comment by nbara** [comment]
Hey John, thanks for this! I will have a look asap. The doc build job should be an easy fix

**Comment by nbara** [comment]
Hi @johnkylecooper, the example looks great. 

FWIW, you don't need to generate both the `example_*.ipynb` example AND the `example_*.py` files. 

Just do you code in the .py file, and run `make build-examples` and the notebooks will be automatically generated from the .py files (including headers and sections). 

Again, thanks for the contribution. I don't use the code in `meegkit` that much these days for my own work but I'm happy to keep maintaining it if it helps others 🙂  

PS: the doc build fails it comes from a fork. It's a CI bug, nothing to do with your example.

**Comment by nbara** [comment]
https://nbara.github.io/python-meegkit/auto_examples/example_mcca_2.html#sphx-glr-auto-examples-example-mcca-2-py  looking good ! ;)

**Comment by johnkylecooper** [comment]
> https://nbara.github.io/python-meegkit/auto_examples/example_mcca_2.html#sphx-glr-auto-examples-example-mcca-2-py looking good ! ;)

Thanks! :)

> Hi @johnkylecooper, the example looks great.
> 
> FWIW, you don't need to generate both the `example_*.ipynb` example AND the `example_*.py` files.
> 
> Just do you code in the .py file, and run `make build-examples` and the notebooks will be automatically generated from the .py files (including headers and sections).
> 
> Again, thanks for the contribution. I don't use the code in `meegkit` that much these days for my own work but I'm happy to keep maintaining it if it helps others 🙂
> 
> PS: the doc build fails it comes from a fork. It's a CI bug, nothing to do with your example.

Also, thanks for the tips! :)
Yes, I mainly use meegkit for the preprocessing tools (for eeg recordings) and now mcca. It's very handy! I have a lot of respect for you guys who maintain open-source projects! I hope to be able to contribute more to projects in the future!

Going to delete my branch and delete the fork now.

Best,
John Kyle

**Pull request merged**
